<?php
/**
 * @package Intelipost\Shipping
 * @copyright Copyright (c) 2021 Intelipost
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */
?>

<script>
    window.intelipost_calendar_url = "<?= $this->getAjaxCalendarUrl(); ?>";
    window.intelipost_schedule_url = "<?= $this->getAjaxScheduleUrl(); ?>";
    window.intelipost_schedule_status_url = "<?= $this->getAjaxScheduleStatusUrl(); ?>";
</script>

