<?php
/*
 * @package     Intelipost_Shipping
 * @copyright   Copyright (c) 2021 - Intelipost (https://intelipost.com.br)
 * @author      Intelipost Team
 */
?>

<script>
    window.intelipost_calendar_url = "<?php echo $this->getAjaxCalendarUrl(); ?>";
    window.intelipost_schedule_url = "<?php echo $this->getAjaxScheduleUrl(); ?>";
    window.intelipost_schedule_status_url = "<?php echo $this->getAjaxScheduleStatusUrl(); ?>";
</script>

