<?php
/**
 * @package Intelipost\Shipping
 * @copyright Copyright (c) 2021 Intelipost
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>

<table class="product-shipping-table">
    <tr>
        <td class="message error"><?= $block->escapeHtml(__('There was an error with the shipping quote, please contact us')) ?></td>
    </tr>
</table>

